#!/bin/env bash

################################################################################
###	CHECK SCRIPT INVOCATION AND SET CONSTANTS
################################################################################

### CHECK FOR ROOT USER
if [[ $(whoami) != "root" ]]; then
	echo "ERROR! Script needs root access. Please run as sudo";
	exit 0;
fi;

### ENSURE THAT THE SCRIPT IS CALLED WITH PARAMETERS
if [[ $1 == "" ]]; then
	echo "Usage:   fixperms <username> <path>";
	echo "Example: mkvhostrepo username .";
	echo "         will set permissions as username:_www on all files and folders within <path>";
	echo "         and set file and folder permissions to 0775 0664";
	echo "         Second parameter <path> is optionsl, defaults to .";
	exit 0;
fi

### CHECK EXISTANCE OF SECOND PARAM
if [[ $2 != "" ]]; then
	DIR=$2;
else
	DIR=$(pwd);
fi

### CREATE VARIABLES
USER=$1;
GROUP="_www";



################################################################################
###	RUN SCRIPT
################################################################################

### DOUBLE CHECK
bool="n";
echo -n "Warning: This will set permissions and owner on ${DIR} Are you sure? ";
read bool;
if [[ ${bool} == "y" || ${bool} == "Y" || ${bool} == "yes" || ${bool} == "YES" || ${bool} == "Yes" ]]; then

	echo "Setting owner:group to ${USER}:${GROUP} on ${DIR}";
	chown -R ${USER}:${GROUP} ${DIR};

	echo "Setting permissions on ${DIR}";
	while IFS= read -r N;
	do
		chmod -R 775 "${N}" || echo "Failed on ${N}";
	done < <(find ${DIR} -type d);

	while IFS= read -r N;
	do
		chmod 664 "${N}" || echo "Failed on ${N}";
	done < <(find ${DIR} -type f);

	while IFS= read -r N;
	do
		chmod 664 "${N}" || echo "Failed on ${N}";
	done < <(find ${DIR} -type l);
else
	exit 0;
fi



################################################################################
### FINISHED OUTPUT
################################################################################

echo "Completed.";
